/**
 * Browserbase Deployer - Deploy tests as Browser Functions
 */

import { writeFile, mkdir, rm } from 'fs/promises';
import { join } from 'path';
import { exec } from 'child_process';
import { promisify } from 'util';
import type { TestDefinition, DeploymentResult } from './types.js';

const execAsync = promisify(exec);

const BB_API = 'https://api.browserbase.com/v1';

/**
 * Convert a test definition into a Browser Function code string
 */
function generateFunctionCode(test: TestDefinition): string {
  const viewport = test.viewport || { width: 1920, height: 1080 };

  return `import { defineFn } from "@browserbasehq/sdk-functions";
import { chromium } from "playwright-core";
import { expect } from "@playwright/test";

defineFn("${test.id}", async (ctx, params) => {
  const browser = await chromium.connectOverCDP(ctx.session.connectUrl);
  const context = browser.contexts()[0];
  const page = context?.pages()[0];

  if (!page) {
    return {
      success: false,
      testId: "${test.id}",
      error: "No page available"
    };
  }

  const sessionUrl = \`https://www.browserbase.com/sessions/\${ctx.session.id}\`;

  try {
    // Test code generated by Claude
    ${test.code}

    // Capture final screenshot for visual regression
    const finalScreenshot = await page.screenshot({
      encoding: "base64",
      fullPage: true
    });

    return {
      success: true,
      testId: "${test.id}",
      testName: "${test.name}",
      sessionId: ctx.session.id,
      sessionUrl,
      finalScreenshot
    };
  } catch (error) {
    // Capture error state screenshot
    const finalScreenshot = await page.screenshot({ encoding: "base64" }).catch(() => null);

    return {
      success: false,
      testId: "${test.id}",
      testName: "${test.name}",
      error: String(error),
      sessionId: ctx.session.id,
      sessionUrl,
      finalScreenshot
    };
  }
}, {
  sessionConfig: {
    browserSettings: { advancedStealth: true },
    viewport: { width: ${viewport.width}, height: ${viewport.height} }
  }
});
`;
}

/**
 * Generate an index file that imports all function files
 */
function generateIndexFile(tests: TestDefinition[]): string {
  // Use .ts extension since we're using TypeScript
  const imports = tests.map((_, i) => `import './fn_${i}.ts';`).join('\n');
  return imports;
}

/**
 * Deploy tests as Browser Functions to Browserbase
 */
export async function deployTests(tests: TestDefinition[]): Promise<DeploymentResult> {
  if (tests.length === 0) {
    return {
      buildId: '',
      functionIds: new Map()
    };
  }

  const apiKey = process.env.BROWSERBASE_API_KEY;
  const projectId = process.env.BROWSERBASE_PROJECT_ID;

  if (!apiKey || !projectId) {
    throw new Error('BROWSERBASE_API_KEY and BROWSERBASE_PROJECT_ID are required');
  }

  // Create temp directory for function files
  const tempDir = join(process.cwd(), '.bb-functions-temp');
  await mkdir(tempDir, { recursive: true });

  try {
    // Write function files
    for (let i = 0; i < tests.length; i++) {
      const code = generateFunctionCode(tests[i]);
      await writeFile(join(tempDir, `fn_${i}.ts`), code);
    }

    // Write index file
    const indexCode = generateIndexFile(tests);
    await writeFile(join(tempDir, 'index.ts'), indexCode);

    // Write package.json
    await writeFile(join(tempDir, 'package.json'), JSON.stringify({
      name: 'pr-test-functions',
      type: 'module',
      dependencies: {
        '@browserbasehq/sdk-functions': '^0.0.5',
        '@playwright/test': '^1.50.0',
        'playwright-core': '^1.50.0'
      }
    }, null, 2));

    // Write tsconfig.json for TypeScript support
    await writeFile(join(tempDir, 'tsconfig.json'), JSON.stringify({
      compilerOptions: {
        target: 'ES2022',
        module: 'NodeNext',
        moduleResolution: 'NodeNext',
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true
      },
      include: ['*.ts']
    }, null, 2));

    // Write .env file for CLI
    await writeFile(join(tempDir, '.env'), `
BROWSERBASE_API_KEY=${apiKey}
BROWSERBASE_PROJECT_ID=${projectId}
`.trim());

    console.log(`Generated ${tests.length} function files in ${tempDir}`);

    // Install dependencies and publish
    console.log('Installing dependencies...');
    await execAsync('npm install', { cwd: tempDir });

    console.log('Publishing functions to Browserbase...');
    const { stdout, stderr } = await execAsync('npx bb publish index.ts', {
      cwd: tempDir,
      env: {
        ...process.env,
        BROWSERBASE_API_KEY: apiKey,
        BROWSERBASE_PROJECT_ID: projectId
      }
    });

    console.log('Publish output:', stdout);
    if (stderr) {
      console.error('Publish stderr:', stderr);
    }

    // Parse build ID from output
    const buildIdMatch = stdout.match(/Build ID:\s*(\S+)/i) || stdout.match(/build[_-]?id[:\s]+(\S+)/i);
    const buildId = buildIdMatch?.[1] || `build-${Date.now()}`;

    // Parse function IDs directly from CLI output
    // Format: "1. function-name\n   Function ID: uuid"
    const functionIds = new Map<string, string>();
    const functionPattern = /^\d+\.\s+(\S+)\s*\n\s*Function ID:\s*(\S+)/gm;
    let match;
    while ((match = functionPattern.exec(stdout)) !== null) {
      const [, name, id] = match;
      functionIds.set(name, id);
      console.log(`Parsed function: ${name} -> ${id}`);
    }

    // Fallback: try API if we didn't parse any functions
    if (functionIds.size === 0) {
      console.log('No functions parsed from CLI output, trying API...');
      const apiFunctions = await getFunctionIdsFromBuild(buildId, apiKey);
      for (const [name, id] of apiFunctions) {
        functionIds.set(name, id);
      }
    }

    console.log(`Total functions deployed: ${functionIds.size}`);

    return {
      buildId,
      functionIds
    };
  } finally {
    // Clean up temp directory
    await rm(tempDir, { recursive: true, force: true }).catch(() => {});
  }
}

/**
 * Get function IDs from a completed build
 */
async function getFunctionIdsFromBuild(
  buildId: string,
  apiKey: string
): Promise<Map<string, string>> {
  const functionIds = new Map<string, string>();

  try {
    // Get build info
    const response = await fetch(`${BB_API}/functions/builds/${buildId}`, {
      headers: {
        'x-bb-api-key': apiKey
      }
    });

    if (!response.ok) {
      console.warn(`Failed to get build info: ${response.status}`);
      return functionIds;
    }

    const build = await response.json() as {
      builtFunctions?: Array<{ id: string; name: string }>;
    };

    console.log('Build API response:', JSON.stringify(build, null, 2));

    if (build.builtFunctions) {
      for (const fn of build.builtFunctions) {
        functionIds.set(fn.name, fn.id);
        console.log(`Found function from API: ${fn.name} -> ${fn.id}`);
      }
    }
  } catch (error) {
    console.warn('Failed to get function IDs from build:', error);
  }

  return functionIds;
}

/**
 * Alternative: Deploy using direct API instead of CLI
 * This could be used if the CLI approach doesn't work in GHA
 */
export async function deployTestsViaAPI(tests: TestDefinition[]): Promise<DeploymentResult> {
  const apiKey = process.env.BROWSERBASE_API_KEY;
  const projectId = process.env.BROWSERBASE_PROJECT_ID;

  if (!apiKey || !projectId) {
    throw new Error('BROWSERBASE_API_KEY and BROWSERBASE_PROJECT_ID are required');
  }

  // For now, this is a placeholder - the actual API for deploying functions
  // may differ. The CLI approach is more reliable for bundling dependencies.

  console.warn('API-based deployment not yet implemented, falling back to CLI');
  return deployTests(tests);
}
