/**
 * PR Reporter - Format and post test results as GitHub PR comment
 */

import { Octokit } from '@octokit/rest';
import type { TestResult, AnalysisResult, ReportData } from './types.js';

const COMMENT_MARKER = '<!-- pr-test-agent-report -->';

/**
 * Format test results as a markdown report
 */
function formatReport(data: ReportData): string {
  const { results, analysis, previewUrl, duration } = data;

  const passed = results.filter((r) => r.success).length;
  const failed = results.filter((r) => !r.success).length;
  const total = results.length;

  const statusEmoji = failed > 0 ? '❌' : '✅';
  const statusText = failed > 0 ? 'Some tests failed' : 'All tests passed';

  let report = `${COMMENT_MARKER}
## ${statusEmoji} PR Test Agent Report

**Status:** ${statusText}
**Preview URL:** ${previewUrl}
**Duration:** ${(duration / 1000).toFixed(1)}s

### Summary
| Passed | Failed | Total |
|--------|--------|-------|
| ✅ ${passed} | ❌ ${failed} | ${total} |

### Changed Flows Detected
${analysis.changedFlows.length > 0 ? analysis.changedFlows.map((f) => `- ${f}`).join('\n') : '_No flow changes detected_'}

### Test Results

| Test | Status | Duration | Session |
|------|--------|----------|---------|
${results.map((r) => `| ${r.testId} | ${r.success ? '✅' : '❌'} | ${r.duration}ms | [View](${r.sessionUrl}) |`).join('\n')}
`;

  // Add failure details
  const failures = results.filter((r) => !r.success);
  if (failures.length > 0) {
    report += `
### Failures

${failures.map((r) => `
<details>
<summary>❌ <strong>${r.testId}</strong></summary>

**Error:**
\`\`\`
${r.error || 'Unknown error'}
\`\`\`

**🎬 Session Replay:** [View in Browserbase](${r.sessionUrl})

${r.finalScreenshot ? `
**Screenshot at failure:**

<img src="data:image/png;base64,${r.finalScreenshot}" width="600" />
` : ''}

</details>
`).join('\n')}
`;
  }

  // Add visual regression section
  const withScreenshots = results.filter((r) => r.finalScreenshot);
  if (withScreenshots.length > 0) {
    report += `
### Visual Regression Screenshots

<details>
<summary>📸 View ${withScreenshots.length} screenshots</summary>

${withScreenshots.map((r) => `
#### ${r.success ? '✅' : '❌'} ${r.testId}

<img src="data:image/png;base64,${r.finalScreenshot}" width="600" />

`).join('\n')}

</details>
`;
  }

  // Add analysis summary
  if (analysis.summary) {
    report += `
### Analysis Summary

${analysis.summary}
`;
  }

  // Add new tests info
  if (analysis.testsToAdd.length > 0) {
    report += `
### New Tests Added

${analysis.testsToAdd.map((t) => `- **${t.id}**: ${t.description}`).join('\n')}
`;
  }

  // Add modified tests info
  if (analysis.testsToModify.length > 0) {
    report += `
### Tests Modified

${analysis.testsToModify.map((m) => `- **${m.testId}**: ${m.reason}`).join('\n')}
`;
  }

  report += `
---
*Generated by [PR Test Agent](https://github.com/your-org/pr-test-agent) using Claude + Browserbase*
`;

  return report;
}

/**
 * Post or update the test report comment on a PR
 */
export async function reportResults(
  results: TestResult[],
  analysis: AnalysisResult,
  previewUrl: string,
  duration: number
): Promise<void> {
  const token = process.env.GITHUB_TOKEN;
  const prNumber = parseInt(process.env.PR_NUMBER || '0', 10);
  const [owner, repo] = (process.env.GITHUB_REPOSITORY || '/').split('/');

  if (!token) {
    console.warn('GITHUB_TOKEN not set, skipping PR comment');
    console.log('\n--- Test Report ---\n');
    console.log(formatReport({ results, analysis, previewUrl, duration }));
    return;
  }

  if (!prNumber || !owner || !repo) {
    console.warn('PR context not available, skipping PR comment');
    console.log('\n--- Test Report ---\n');
    console.log(formatReport({ results, analysis, previewUrl, duration }));
    return;
  }

  const octokit = new Octokit({ auth: token });
  const body = formatReport({ results, analysis, previewUrl, duration });

  try {
    // Find existing comment
    const { data: comments } = await octokit.issues.listComments({
      owner,
      repo,
      issue_number: prNumber,
      per_page: 100
    });

    const existingComment = comments.find((c) =>
      c.body?.includes(COMMENT_MARKER)
    );

    if (existingComment) {
      // Update existing comment
      await octokit.issues.updateComment({
        owner,
        repo,
        comment_id: existingComment.id,
        body
      });
      console.log(`Updated PR comment: ${existingComment.html_url}`);
    } else {
      // Create new comment
      const { data: newComment } = await octokit.issues.createComment({
        owner,
        repo,
        issue_number: prNumber,
        body
      });
      console.log(`Created PR comment: ${newComment.html_url}`);
    }
  } catch (error) {
    console.error('Failed to post PR comment:', error);
    // Still output the report to console
    console.log('\n--- Test Report ---\n');
    console.log(body);
  }
}

/**
 * Post a simple status comment (for errors or early exits)
 */
export async function reportError(
  errorMessage: string,
  previewUrl?: string
): Promise<void> {
  const token = process.env.GITHUB_TOKEN;
  const prNumber = parseInt(process.env.PR_NUMBER || '0', 10);
  const [owner, repo] = (process.env.GITHUB_REPOSITORY || '/').split('/');

  const body = `${COMMENT_MARKER}
## ❌ PR Test Agent Error

An error occurred while running tests:

\`\`\`
${errorMessage}
\`\`\`

${previewUrl ? `**Preview URL:** ${previewUrl}` : ''}

---
*Generated by [PR Test Agent](https://github.com/your-org/pr-test-agent)*
`;

  if (!token || !prNumber || !owner || !repo) {
    console.error('Cannot post error to PR:', errorMessage);
    return;
  }

  const octokit = new Octokit({ auth: token });

  try {
    await octokit.issues.createComment({
      owner,
      repo,
      issue_number: prNumber,
      body
    });
  } catch (error) {
    console.error('Failed to post error comment:', error);
  }
}
